import { ModalItem } from 'src/app/modules/client/pages/service-points/service-points.component';
import { Gender } from '../enums/gender.enum';

export enum ServiceListCategoryToShow {
  SINGLE = 'single',
  MULTIPLE = 'multiple',
  BOTH = 'both',
}

export const ModalArray: ModalItem[] = [
  {
    id: 'health-education',
    title: 'Health Education',
    siSwati: 'Tinhlelo',
    icon: '/assets/icon/health-education.png',
    children: null,
    cssClass: 'service-card',
    category: ServiceListCategoryToShow.BOTH,
    gender: 4,
  },
  {
    id: 'anc',
    title: 'ANC',
    siSwati: 'Tinhlelo talabatetfwele',
    icon: '/assets/icon/service/anc.png',
    children: [
      {
        id: 'anc-initiation',
        title: 'ANC Initiation',
        siSwati: 'Bhalisela ku-Klinikhela kutetfwala',
        icon: '/assets/icon/service/anc-initiation.png',
        children: null,
        cssClass: 'service-card',
        category: ServiceListCategoryToShow.SINGLE,
        gender: 4,
      },
      {
        id: 'anc-topics',
        title: 'ANC Topics',
        siSwati: 'Tifundvo teku-Klinikha kwalabatetfwele',
        icon: '/assets/icon/service/anc-topics.png',
        children: null,
        cssClass: 'service-card',
        category: ServiceListCategoryToShow.SINGLE,
        gender: 4,
      },
    ],
    cssClass: 'service-card',
    category: ServiceListCategoryToShow.SINGLE,
    gender: Gender.Female,
  },
  {
    id: 'family-planning',
    title: 'Family Planning',
    siSwati: 'Kuhlela Umndeni',
    icon: '/assets/icon/service/family-planing.png',
    children: null,
    cssClass: 'service-card',
    category: ServiceListCategoryToShow.SINGLE,
    gender: 4,
  },
  {
    id: 'child-health',
    title: 'Child Health',
    siSwati: 'Imphilo Yebantfwana',
    icon: '/assets/icon/service/child-health.png',
    children: [
      {
        id: 'child-growth-monitoring',
        title: 'Child Growth Monitoring',
        siSwati: 'Kulandzelela kukhula kwemntfwana',
        icon: '/assets/icon/service/child-health-Growth.png',
        children: null,
        cssClass: 'service-card',
        category: ServiceListCategoryToShow.SINGLE,
        gender: 4,
      },
      {
        id: 'child-immunization',
        title: 'Child Immunization',
        siSwati: 'Kugomiswa kwebantfwana',
        icon: '/assets/icon/service/child-health-Immunization.png',
        children: null,
        cssClass: 'service-card',
        category: ServiceListCategoryToShow.SINGLE,
        gender: 4,
      },
    ],
    cssClass: 'service-card',
    category: ServiceListCategoryToShow.SINGLE,
    gender: 4,
  },
  {
    id: 'postnatal',
    title: 'Postnatal',
    siSwati: 'Make losandza kubeleka',
    icon: '/assets/icon/service/postnatal.png',
    children: [
      {
        id: 'postnatal-preventative',
        title: 'Postnatal Preventative',
        siSwati: 'Luhlelo lekuphephisa lobelekile',
        icon: '/assets/icon/service/postnatal.png',
        children: null,
        cssClass: 'service-card',
        category: ServiceListCategoryToShow.SINGLE,
        gender: 4,
      },
      {
        id: 'postnatal-danger',
        title: 'Postnatal Danger',
        siSwati: 'Ingoti ngemuva kwekubeleka',
        icon: '/assets/icon/service/infection-control.png',
        children: null,
        cssClass: 'service-card',
        category: ServiceListCategoryToShow.SINGLE,
        gender: 4,
      },
      {
        id: 'postnatal-depressions',
        title: 'Postnatal Depressions',
        siSwati: 'Kukhatsateka nekungajabuli kwalobelekile',
        icon: '/assets/icon/service/child-health-Immunization.png',
        children: null,
        cssClass: 'service-card',
        category: ServiceListCategoryToShow.SINGLE,
        gender: 4,
      },
      {
        id: 'postnatal-feeding',
        title: 'Postnatal Feeding',
        siSwati: 'Kondliwa kweluswane',
        icon: '/assets/icon/service/child-health.png',
        children: null,
        cssClass: 'service-card',
        category: ServiceListCategoryToShow.SINGLE,
        gender: 4,
      },
    ],
    cssClass: 'service-card',
    category: ServiceListCategoryToShow.SINGLE,
    gender: 4,
  },
  {
    id: 'household-nutrition',
    title: 'Household Nutrition',
    siSwati: 'Kuhlukahluka kwekudla',
    icon: '/assets/icon/service/nutrition.png',
    children: [
      {
        id: 'dietary-diversity',
        title: 'Dietary Diversity',
        siSwati: 'Kuhlukahluka kwekudla',
        icon: '/assets/icon/service/Dietary.png',
        children: null,
        cssClass: 'service-card',
        category: ServiceListCategoryToShow.SINGLE,
        gender: 4,
      },
      {
        id: 'breastfeeding-complimentary',
        title: 'Breastfeeding & Complimentary',
        siSwati: 'Lomunyisa abhice nalokicinile',
        icon: '/assets/icon/service/breastfeeding.png',
        children: null,
        cssClass: 'service-card',
        category: ServiceListCategoryToShow.SINGLE,
        gender: 4,
      },
      {
        id: 'minimum-acceptable-diet',
        title: 'Minimum Acceptable Diet',
        siSwati: 'Lizinga lekudla lelijabulisako',
        icon: '/assets/icon/service/minimum-acceptable-diet.png',
        children: null,
        cssClass: 'service-card',
        category: ServiceListCategoryToShow.SINGLE,
        gender: 4,
      },
    ],
    cssClass: 'service-card',
    category: ServiceListCategoryToShow.BOTH,
    gender: 4,
  },
  {
    id: 'hiv-services',
    title: 'HIV Services',
    siSwati: 'Tinsita Te-HIV',
    icon: '/assets/icon/service/hiv-services.png',
    children: [
      {
        id: 'counseling',
        title: 'Counseling',
        siSwati: 'Kukhokhelwa',
        icon: '/assets/icon/service/Counseling.png',
        children: null,
        cssClass: 'service-card',
        category: ServiceListCategoryToShow.SINGLE,
        gender: 4,
      },
      {
        id: 'self-test',
        title: 'Self Test',
        siSwati: 'Kwekutihlola Simo se HIV',
        icon: '/assets/icon/service/self-test.png',
        children: null,
        cssClass: 'service-card',
        category: ServiceListCategoryToShow.SINGLE,
        gender: 4,
      },
    ],
    cssClass: 'service-card',
    category: ServiceListCategoryToShow.BOTH,
    gender: 4,
  },
  {
    id: 'art',
    title: 'ART',
    siSwati: 'Kudvubutwa ngemaphilisi',
    icon: '/assets/icon/service/art.png',
    children: null,
    cssClass: 'service-card',
    category: ServiceListCategoryToShow.BOTH,
    gender: 4,
  },
  {
    id: 'tb-services',
    title: 'TB Services',
    siSwati: 'Kukhalima kubhedvuka kwe TB',
    icon: '/assets/icon/service/tb-services.png',
    children: [
      {
        id: 'infection-control',
        title: 'Infection Control',
        siSwati: 'Kukhalima kubhedvuka kwe TB',
        icon: '/assets/icon/service/infection-control.png',
        children: null,
        cssClass: 'service-card',
        category: ServiceListCategoryToShow.SINGLE,
        gender: 4,
      },
      {
        id: 'symptoms-screening',
        title: 'Symptom Screening',
        siSwati: 'Kuhlolwa kwetimphawu te TB',
        icon: '/assets/icon/service/symptoms-screening.png',
        children: null,
        cssClass: 'service-card',
        category: ServiceListCategoryToShow.SINGLE,
        gender: 4,
      },
      {
        id: 'environment-assessment',
        title: 'Environment Assessment',
        siSwati: 'Kuhlola kuhloba kwelikhaya',
        icon: '/assets/icon/service/environment-assessment.png',
        children: null,
        cssClass: 'service-card',
        category: ServiceListCategoryToShow.SINGLE,
        gender: 4,
      },
      {
        id: 'tb-discussed-topic',
        title: 'TB Discussed Topic',
        siSwati: 'Timfundziso te TB letentiwe',
        icon: '/assets/icon/service/tb-discussed-topic.png',
        children: null,
        cssClass: 'service-card',
        category: ServiceListCategoryToShow.SINGLE,
        gender: 4,
      },
    ],
    cssClass: 'service-card',
    category: ServiceListCategoryToShow.SINGLE,
    gender: 4,
  },
  {
    id: 'malaria-services',
    title: 'Malaria Services',
    siSwati: 'Lowamukelisa ema-nethi eMalaria',
    icon: '/assets/icon/service/malaria-services.png',
    children: [
      {
        id: 'malaria-risks',
        title: 'Malaria Risks',
        siSwati: 'Lokubhebhetela Malaria',
        icon: '/assets/icon/service/malaria-risks.png',
        children: null,
        cssClass: 'service-card',
        category: ServiceListCategoryToShow.SINGLE,
        gender: 4,
      },
      {
        id: 'malaria-symptoms',
        title: 'Malaria Symptoms',
        siSwati: 'Tmphawu te Malaria',
        icon: '/assets/icon/service/malaria-services.png',
        children: null,
        cssClass: 'service-card',
        category: ServiceListCategoryToShow.SINGLE,
        gender: 4,
      },
      {
        id: 'case-finding',
        title: 'Case Finding',
        siSwati: 'Kubamba lonaMalaria',
        icon: '/assets/icon/service/case-finding.png',
        children: null,
        cssClass: 'service-card',
        category: ServiceListCategoryToShow.SINGLE,
        gender: 4,
      },
      {
        id: 'malaria-prevention',
        title: 'Malaria Prevention',
        siSwati: 'Kuvikelwa kwaMalaria',
        icon: '/assets/icon/service/malaria-prevention.png',
        children: null,
        cssClass: 'service-card',
        category: ServiceListCategoryToShow.SINGLE,
        gender: 4,
      },
      {
        id: 'control-intervention',
        title: 'Control Intervention',
        siSwati: 'kuvikela kubhebheteleka',
        icon: '/assets/icon/service/control-intervention.png',
        children: null,
        cssClass: 'service-card',
        category: ServiceListCategoryToShow.SINGLE,
        gender: 4,
      },
    ],
    cssClass: 'service-card',
    category: ServiceListCategoryToShow.BOTH,
    gender: 4,
  },

  {
    id: 'hbc',
    title: 'HBC Services',
    siSwati: 'Tihlelo talabagulela ekhaya',
    icon: '/assets/icon/service/hbc.png',
    children: [
      {
        id: 'hbc-service',
        title: 'HBC Services',
        siSwati: 'Tihlelo talabagulela ekhaya',
        icon: '/assets/icon/service/hbc-service.png',
        children: null,
        cssClass: 'service-card',
        category: ServiceListCategoryToShow.SINGLE,
        gender: 4,
      },
      {
        id: 'client-assessment',
        title: 'Client Assessment',
        siSwati: 'Kucwaninga logulela ekhaya',
        icon: '/assets/icon/service/client-assessment.png',
        children: null,
        cssClass: 'service-card',
        category: ServiceListCategoryToShow.SINGLE,
        gender: 4,
      },
    ],
    cssClass: 'service-card',
    category: ServiceListCategoryToShow.SINGLE,
    gender: 4,
  },
  {
    id: 'ncd',
    title: 'NCD',
    siSwati: 'Tifo letingatsatselwana',
    icon: '/assets/icon/service/ncd.png',
    children: [
      {
        id: 'ncd-history',
        title: 'NCD History',
        siSwati: 'Tifo letingatsatselwana',
        icon: '/assets/icon/service/ncd-history.png',
        children: null,
        cssClass: 'service-card',
        category: ServiceListCategoryToShow.SINGLE,
        gender: 4,
      },
      {
        id: 'ncd-screening',
        title: 'NCD Screening',
        siSwati: 'Tifo letingatsatselwana',
        icon: '/assets/icon/service/ncd-history.png',
        children: null,
        cssClass: 'service-card',
        category: ServiceListCategoryToShow.SINGLE,
        gender: 4,
      },
    ],
    cssClass: 'service-card',
    category: ServiceListCategoryToShow.SINGLE,
    gender: 4,
  },
];
